---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: alertmanager-statuspage
  name: alertmanager-statuspage
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: alertmanager-statuspage
  type: ClusterIP
